### ISSUE TITLE
Upgrade to GeoStyler v5

### ISSUE THREAD

**Issue by chrismayer** [geostyler/geostyler-demo#173]
# Feature Request

The demo application needs an upgrade to the recently released [GeoStyler v5](https://github.com/geostyler/geostyler/releases/tag/v5.0.0). Since this introduces some major (breaking) changes (upgrade antd to v4) this needs some work.

There is a work-in-progress PR #172, which started to do some upgrade work but needs more love. Check the PR for more information.

**Comment by KaiVolland** [comment]
I'll have a look at it.

**Comment by chrismayer** [comment]
Thanks for your work on this @KaiVolland!

Closed by #172
