### ISSUE TITLE
Not able to understand if `GeoJSON` or `Shapefile` is uploaded successfully 

### ISSUE THREAD

**Issue by krishnaglodha** [geostyler/geostyler-demo#323]
# Bug

**Describe the bug**
I'm trying to use my own data on demo, when I upload the file, it shows loader icon stating the file is loading, and icon stays there forever. I'm able to confirm that file is uploaded and all column names can be seen in list
**To Reproduce**
1. Go to '[demo](https://geostyler.github.io/geostyler-demo/)'
2. Click on 'Load data - `GeoJSON data parser` and drag file'

**Expected behavior**
Success symbol or some sort of text that indicates that file is added. 
**Screenshots**

<img width="525" alt="Screenshot 2022-06-07 at 9 04 49 PM" src="https://user-images.githubusercontent.com/47075664/172421887-c0171a85-2276-4aaf-857e-28f62b1b7826.png">

**Desktop (please complete the following information):**
 - OS: macOs 12.4
 - Browser : Chrome

**Comment by jansule** [comment]
Thanks for the info. I will take a look at this.
