### ISSUE TITLE
Filter UI is broken in Demo

### ISSUE THREAD

**Issue by jansule** [geostyler/geostyler-demo#343]
# Bug

**Describe the bug**

In the current demo, the Filter UI is broken. It is not possible to change the filter type.

**To Reproduce**
1. Click on the edit filter button
2. Click on the tree dots next to the input fields
3. See a small white box with no content opening

**Expected behavior**

I would expect the filter type selection.

**Screenshots**

![image](https://user-images.githubusercontent.com/12186477/173523917-03b823fa-2fa4-498b-af27-2d94ef9b895f.png)

**Desktop (please complete the following information):**
 - OS: [linux mint]
 - Browser [chrome, firefox]
 - Version []

**Smartphone (please complete the following information):**

**Additional context**

Looks like the filter works properly in the [interactive documentation](https://geostyler.github.io/geostyler/latest/index.html#/Components/Style/Style) of geostyler. So it really looks like this is a bug in the demo.

**Comment by OSHistory** [comment]
Seems like someone has fixed that, but the issue is still open.

**Comment by KaiVolland** [comment]
Thanks for the report. :)
