### ISSUE TITLE
Upload Data clear icon does not remove the data

### ISSUE THREAD

**Issue by KaiVolland** [geostyler/geostyler-demo#405]
When uploading data to the GeoStyler Demo a list with the uploaded files is created.
Every item in the list contains a trashcan icon to remove the data. But it acutally does nothing.

We shoul add code that removes the data from the demo when the button is clicked.
Maybe we fist need to add this listener in the geostyler component itself.

**Comment by OSHistory** [comment]
Seems like this issue has been taken care of in the meantime (trash icon actually trashes)

**Comment by KaiVolland** [comment]
Thanks for pointing this out.
