### ISSUE TITLE
Activating SLD renderer breaks demo application

### ISSUE THREAD

**Issue by chrismayer** [geostyler/geostyler-demo#507]
# Bug

**Describe the bug**
When switching to the SLD renderer by clicking the corresponding button in the demo UI the application throws an error in the console (`Error: "wmsBaseUrl" or "layer" are missing in the GeoStylerContext.composition.SLDRenderer`) and the application turns into a white page.

**To Reproduce**
1. Go to https://geostyler.github.io/geostyler-demo/
2. Click on `SLD` in the `Symbolizer Renderer` section in the UI
3. See white page and the error message in the browser console

**Expected behavior**
SLD renderer is used and the application still works as expected.

**Screenshots**
![image](https://github.com/geostyler/geostyler-demo/assets/1185547/915201aa-db6b-4721-97b1-b2f10745f728)

**Desktop**
 - OS: Linux Mint 20
 - Browser: Chromium
 - Version 115.0.5790.17

**Comment by KaiVolland** [comment]
I'll have a look at it.

**Comment by KaiVolland** [comment]
This is also needed to realy fix it: https://github.com/geostyler/geostyler-demo/pull/509
